name: ircproxy
version: 0.1
summary: A minimal IRC proxy using bip
description: |
    Run the bip IRC proxy in a snap.
    The snap puts a default configuration in place and generates a fresh ssl key on first startup.
    .
    To configure the service edit the generated config in /var/snap/ircproxy/current/bip.conf
    And restart the service with "sudo snap restart ircproxy"
    .
    To generate an IRC password to use with the config the snap also ships the "ircproxy.bipmkpw" tool.

confinement: strict
grade: stable

apps:
  ircproxy:
    command: run-bip
    daemon: simple
    plugs: [network, network-bind]
  bipmkpw:
    command: usr/bin/bipmkpw

parts:
  ircproxy:
    plugin: dump
    prime:
      - run-bip
      - config.sh
      - default.yaml
      - etc
      - lib
      - usr
    stage-packages:
      - bip
      - openssl
