name: ircproxy
adopt-info: bip
summary: A minimal IRC proxy using bip
description: |
    Run the bip IRC proxy in a snap.
    The snap puts a default configuration in place and generates a fresh ssl key on first startup.
    .
    To configure the service edit the generated config in /var/snap/ircproxy/current/bip.conf
    And restart the service with "sudo snap restart ircproxy"
    .
    To generate an IRC password to use with the config the snap also ships the "ircproxy.bipmkpw" tool.

base: core20
confinement: strict
grade: stable

apps:
  ircproxy:
    command: run-bip
    daemon: simple
    plugs:
      - network
      - network-bind
  bipmkpw:
    command: usr/bin/bipmkpw

layout:
  /etc/ssl:
    bind: $SNAP_DATA/ssl
  /etc/ca-certificates:
    bind: $SNAP/etc/ca-certificates
  /etc/ca-certificates.conf:
    bind-file: $SNAP_DATA/ca-certificates.conf
  /usr/share/ca-certificates:
    bind: $SNAP/usr/share/ca-certificates
  /usr/lib/x86_64-linux-gnu/engines-1.1:
    bind: $SNAP/usr/lib/x86_64-linux-gnu/engines-1.1

parts:
  bip:
    plugin: autotools
    source: https://vcs-git.duckcorp.org/projects/bip/bip.git
    #source-tag: release-0.9.0-rc4
    build-environment:
      - CFLAGS: "-Wno-error"
    autotools-configure-parameters:
      - prefix="/usr"
    override-build: |
      snapcraftctl build
      VER="$(grep AC_INIT configure.ac | cut -d',' -f2 | sed 's/\[//;s/\]//')"
      echo "setting version to $VER"
      snapcraftctl set-version "$VER"
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/doc/bip
      cp COPYING $SNAPCRAFT_PART_INSTALL/usr/share/doc/bip/copyright
    build-packages:
      - libssl-dev
      - pkg-config
    prime:
      - -usr/share/man
      - -usr/share/doc/bip/examples
  ircproxy:
    plugin: dump
    source: .
    after: [ bip ]
    prime:
      - run-bip
      - config.sh
      - default.yaml
      - etc
      - usr
      - -etc/init.d
      - -etc/default
      - -usr/share/man
      - -usr/share/lintian
      - -lib/systemd/system
      - -usr/share/doc/ca-certificates/examples
    override-build: |
      snapcraftctl build
      find $SNAPCRAFT_PART_INSTALL/usr/share/doc -depth -type f,l ! -name copyright|xargs rm
      find $SNAPCRAFT_PART_INSTALL/usr/share/doc -empty|xargs rmdir
    stage-packages:
      - ca-certificates
      - libssl1.1
      - openssl
